inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 101

training:
    # seed: 42 
    # Tony: I think its prob important to seed training, data generation, weight generation, etc. 
    # but don't want to change code too much
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
